ENV['RCT_NEW_ARCH_ENABLED'] = '0'
$RNFirebaseAnalyticsWithoutAdIdSupport = true

def node_require(script)
  require Pod::Executable.execute_command(
    'node',
    ['-p', "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__]
  ).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.1'
prepare_react_native_project!

target 'YogiitsuApp' do
  config = use_native_modules!

  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true

  pod 'GoogleSignIn', '7.1.0'

  setup_permissions(['LocationWhenInUse'])

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end